name: ROS 2 Humble CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:humble
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up ROS environment
        run: |
          echo "source /opt/ros/humble/setup.bash" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          apt update && apt install -y \
            python3-colcon-common-extensions \
            python3-pip \
            git \
            wget \
            unzip \
            build-essential \
            cmake

      - name: Build with colcon
        run: |
          source /opt/ros/humble/setup.bash
          colcon build
