name: Humble CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [humble]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.1
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}

      - name: Build and test
        uses: ros-tooling/action-ros-ci@0.3.5
        with:
          package-name: natnet_ros2
          target-ros2-distro: ${{ matrix.ros_distro }}
          skip-tests: true
